<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="51198" started-at="2018-10-05T11:52:46Z" finished-at="2018-10-05T11:53:37Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="51198" started-at="2018-10-05T11:52:46Z" finished-at="2018-10-05T11:53:37Z">
      <class name="main.java.bank.testcases.EditAccount">
        <test-method status="PASS" signature="init()[pri:0, instance:main.java.bank.testcases.EditAccount@7cd62f43]" name="init" is-config="true" duration-ms="6770" started-at="2018-10-05T11:52:46Z" finished-at="2018-10-05T11:52:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="verifyEditAccount()[pri:0, instance:main.java.bank.testcases.EditAccount@7cd62f43]" name="verifyEditAccount" duration-ms="10179" started-at="2018-10-05T11:52:53Z" finished-at="2018-10-05T11:53:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyEditAccount -->
        <test-method status="PASS" signature="verifyLogOut()[pri:0, instance:main.java.bank.testcases.EditAccount@7cd62f43]" name="verifyLogOut" duration-ms="6818" started-at="2018-10-05T11:53:03Z" depends-on-methods="main.java.bank.testcases.EditAccount.verifyEditAccount" finished-at="2018-10-05T11:53:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogOut -->
        <test-method status="FAIL" signature="verifyUserCreated()[pri:0, instance:main.java.bank.testcases.EditAccount@7cd62f43]" name="verifyUserCreated" duration-ms="26519" started-at="2018-10-05T11:53:10Z" depends-on-methods="main.java.bank.testcases.EditAccount.verifyLogOut" finished-at="2018-10-05T11:53:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://www.demo.guru99.com/v4/customer/Customerhomepage.php] but found [http://www.demo.guru99.com/V4/customer/Customerhomepage.php]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://www.demo.guru99.com/v4/customer/Customerhomepage.php] but found [http://www.demo.guru99.com/V4/customer/Customerhomepage.php]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at main.java.bank.testcases.EditAccount.verifyUserCreated(EditAccount.java:91)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserCreated -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:main.java.bank.testcases.EditAccount@7cd62f43]" name="tearDown" is-config="true" duration-ms="866" started-at="2018-10-05T11:53:36Z" finished-at="2018-10-05T11:53:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- main.java.bank.testcases.EditAccount -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
